name: Online

on:
      push:
            branches:
                  - main

jobs:
      build-and-deploy:
            runs-on: ubuntu-latest
            if: "contains(github.event.head_commit.message, '[online]') || contains(github.event.inputs.tags, '[online]')"
            steps:
                  - name: Sync
                    uses: appleboy/ssh-action@master
                    with:
                          host: ${{ secrets.HOST228 }}
                          username: ${{ secrets.USERNAME }}
                          key: ${{ secrets.SSH_KEY_228 }}
                          port: ${{ secrets.PORT }}
                          command_timeout: 20m
                          script: |
                                cd /app/website/components-doc-zh-CN
                                git pull
